/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author jc_he
 */
public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        iniciarSesionLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        contrasenaLabel = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        botonEntrar = new javax.swing.JPanel();
        entrarLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cerrarText = new javax.swing.JLabel();
        iconoLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 0, 51));
        background.setForeground(new java.awt.Color(204, 204, 204));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarSesionLabel.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        iniciarSesionLabel.setForeground(new java.awt.Color(204, 204, 255));
        iniciarSesionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarSesionLabel.setText("Iniciar sesión");
        background.add(iniciarSesionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 40));

        correoLabel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        correoLabel.setForeground(new java.awt.Color(204, 204, 255));
        correoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correoLabel.setText("Correo electrónico");
        background.add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 800, 20));

        contrasenaLabel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        contrasenaLabel.setForeground(new java.awt.Color(204, 204, 255));
        contrasenaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contrasenaLabel.setText("Contraseña");
        background.add(contrasenaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 280, 790, -1));

        correoTextField.setForeground(new java.awt.Color(153, 153, 153));
        correoTextField.setText("Inserte su correo electrónico");
        correoTextField.setToolTipText("Inserte su correo electrónico");
        correoTextField.setNextFocusableComponent(jPasswordField1);
        correoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoTextFieldFocusLost(evt);
            }
        });
        background.add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 300, 30));

        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("Introduzca su contraseña");
        jPasswordField1.setToolTipText("Introduzca su contraseña");
        jPasswordField1.setNextFocusableComponent(botonEntrar);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        background.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 300, 30));

        botonEntrar.setBackground(new java.awt.Color(153, 153, 255));
        botonEntrar.setForeground(new java.awt.Color(102, 102, 255));
        botonEntrar.setToolTipText("Entrar");
        botonEntrar.setName(""); // NOI18N

        entrarLabel.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        entrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrarLabel.setText("ENTRAR");
        entrarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entrarLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                entrarLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout botonEntrarLayout = new javax.swing.GroupLayout(botonEntrar);
        botonEntrar.setLayout(botonEntrarLayout);
        botonEntrarLayout.setHorizontalGroup(
            botonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(entrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonEntrarLayout.setVerticalGroup(
            botonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(entrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(botonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 370, 150, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cerrarText.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        cerrarText.setForeground(new java.awt.Color(204, 204, 255));
        cerrarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarText.setText("x");
        cerrarText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarText, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cerrarText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 749, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        iconoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/museo.png"))); // NOI18N
        background.add(iconoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 80, -1, -1));
        background.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void cerrarTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarTextMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarTextMouseClicked

    private void cerrarTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarTextMouseEntered
        cerrarText.setForeground(Color.decode("#FF3300"));
    }//GEN-LAST:event_cerrarTextMouseEntered

    private void cerrarTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarTextMouseExited
        cerrarText.setForeground(Color.decode("#CCCCFF"));
    }//GEN-LAST:event_cerrarTextMouseExited

    private void correoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoTextFieldFocusGained
        if (!correoTextField.getForeground().equals(Color.BLACK))
            correoTextField.setText("");
        correoTextField.setForeground(Color.BLACK);
    //    correoTextField.setBorder(null);
    }//GEN-LAST:event_correoTextFieldFocusGained

    private void correoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoTextFieldFocusLost
        if (correoTextField.getText().equals("")
                || !correoTextField.getForeground().equals(Color.BLACK)){
            correoTextField.setText("Introduzca su correo electrónico");
            correoTextField.setForeground(Color.decode("#999999"));
            
        }
    }//GEN-LAST:event_correoTextFieldFocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        if (!jPasswordField1.getForeground().equals(Color.BLACK))
            jPasswordField1.setText("");
        jPasswordField1.setForeground(Color.BLACK);
    //    jPasswordField1.setBorder(null);
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
         if (jPasswordField1.getPassword().length == 0 
                 || !jPasswordField1.getForeground().equals(Color.BLACK)){
            jPasswordField1.setForeground(Color.decode("#999999"));
            jPasswordField1.setText("Inserte su contraseña");
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void entrarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarLabelMouseClicked
        if (correoTextField.getText().equals("")
                || !correoTextField.getForeground().equals(Color.BLACK)){
            correoTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            correoTextField.setToolTipText("Debe introducir un correo electrónico válido.");
        }
        if (jPasswordField1.getPassword().length == 0 
                 || !jPasswordField1.getForeground().equals(Color.BLACK)){
            jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.RED));
            jPasswordField1.setToolTipText("Debe introducir una contraseña válida.");
        }
            
    }//GEN-LAST:event_entrarLabelMouseClicked

    private void entrarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarLabelMousePressed
        botonEntrar.setForeground(Color.decode("#999"));
    }//GEN-LAST:event_entrarLabelMousePressed

    private void entrarLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarLabelMouseReleased
        botonEntrar.setForeground(Color.decode("#99F"));
    }//GEN-LAST:event_entrarLabelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonEntrar;
    private javax.swing.JLabel cerrarText;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JLabel entrarLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel iconoLabel;
    private javax.swing.JLabel iniciarSesionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
